import type { LaunchBatch, Person, PersonId, ResourceLane, StageDef, StageKey, WorkItem, WorkState } from "./types";

export const TODAY = "2026-08-18";

export const STAGES: StageDef[] = [
  { key: "launch", short: "上新", name: "上新时间表", color: "#34C759" },
  { key: "schedule", short: "排期", name: "制片排期表", color: "#007AFF" },
  { key: "produce", short: "制作", name: "制作", color: "#34C759" },
  { key: "upload", short: "上传", name: "上传 SVN", color: "#FF9500" },
  { key: "review", short: "审核", name: "审核", color: "#5856D6" },
  { key: "accept", short: "验收", name: "验收", color: "#30B0C7" },
  { key: "checkin", short: "入库", name: "入库", color: "#FF2D55" },
];

export const PEOPLE: Record<PersonId, Person> = {
  longhui: { id: "longhui", name: "龙慧", title: "上新安排", initials: "龙", hue: 28 },
  xiangbin: { id: "xiangbin", name: "向彬", title: "排期统筹 / 批次主责", initials: "向", hue: 210 },
  linguangyi: { id: "linguangyi", name: "林广益", title: "3D 需求确认", initials: "林", hue: 160 },
  zhongzhiyong: { id: "zhongzhiyong", name: "钟志勇", title: "3D 制作 / 上传 / 入库", initials: "钟", hue: 18 },
  liuxinyu: { id: "liuxinyu", name: "刘心语", title: "平台送审", initials: "刘", hue: 268 },
  hepangpang: { id: "hepangpang", name: "何盼盼", title: "IP 送审", initials: "何", hue: 300 },
  luohaibin: { id: "luohaibin", name: "罗海彬", title: "验收 / 分支同步", initials: "罗", hue: 142 },
  luotianyi: { id: "luotianyi", name: "罗天一", title: "验收协作", initials: "天", hue: 188 },
  chenke: { id: "chenke", name: "陈可", title: "家园文案", initials: "陈", hue: 42 },
  suwan: { id: "suwan", name: "苏晚", title: "平面", initials: "苏", hue: 332 },
  jiangxia: { id: "jiangxia", name: "江夏", title: "常规壁纸", initials: "江", hue: 200 },
  yening: { id: "yening", name: "叶宁", title: "Q 版原画", initials: "叶", hue: 84 },
  hanzhou: { id: "hanzhou", name: "韩舟", title: "Q 版动画", initials: "韩", hue: 352 },
};

function ev(
  id: string,
  at: string,
  actorId: PersonId,
  action: string,
  from?: WorkState,
  to?: WorkState,
  reason?: string,
) {
  return { id, at, actorId, action, from, to, reason };
}

function item(partial: WorkItem): WorkItem {
  return partial;
}

function doneGates(...labels: string[]) {
  return labels.map((label, i) => ({ id: `g${i}`, label, ok: true }));
}

function mixedGates(rows: Array<[string, boolean]>) {
  return rows.map(([label, ok], i) => ({ id: `g${i}`, label, ok }));
}

const histLaunch = [
  ev("h1", "2026-07-28 10:12", "longhui", "确认上线日期", "submitted", "confirmed"),
];
const histSched = [
  ev("h2", "2026-07-30 16:40", "xiangbin", "排期确认", "submitted", "confirmed"),
];

export function seedPrimaryBatch(): LaunchBatch {
  return {
    id: "b-summer",
    name: "2026 夏日家园上新",
    subtitle: "试运行批次 · 模板 v1 快照",
    launchDate: "2026-08-26",
    batchDriId: "xiangbin",
    lanes: [
      {
        id: "q-art",
        name: "Q 版表情原画",
        type: "2D 原画",
        items: [
          item({
            id: "q-art-launch",
            laneId: "q-art",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "上线日 8 月 26 日" },
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("后续节点日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "q-art-schedule",
            laneId: "q-art",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-30",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "yening",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "表情清单 12 个已确认" },
            completeWhen: doneGates("需求表已提交", "人员已确认"),
            enterNextWhen: doneGates("无关键缺失"),
            history: histSched,
          }),
          item({
            id: "q-art-produce",
            laneId: "q-art",
            stage: "produce",
            state: "confirmed",
            dueAt: "2026-08-08",
            offsetLabel: "上线前 12 工作日",
            driId: "yening",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "12 张原画齐套" },
            completeWhen: doneGates("必需内容齐全"),
            enterNextWhen: doneGates("可进入上传"),
            history: [ev("h3", "2026-08-07 18:02", "yening", "提交制作结果", "in_progress", "submitted")],
          }),
          item({
            id: "q-art-upload",
            laneId: "q-art",
            stage: "upload",
            state: "confirmed",
            dueAt: "2026-08-12",
            offsetLabel: "上线前 10 工作日",
            driId: "yening",
            confirmerId: "liuxinyu",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { svnPath: "svn://art/q-emote/draw", svnRev: "18402" },
            completeWhen: doneGates("路径明确", "版本已登记"),
            enterNextWhen: doneGates("解锁审核"),
            history: [ev("h4", "2026-08-11 11:20", "liuxinyu", "确认上传", "submitted", "confirmed")],
          }),
          item({
            id: "q-art-review",
            laneId: "q-art",
            stage: "review",
            state: "submitted",
            dueAt: "2026-08-20",
            offsetLabel: "平台审核预留 4 工作日",
            driId: "liuxinyu",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { svnRev: "18402", note: "已送平台审核，等结论" },
            completeWhen: mixedGates([
              ["送审版本已确认", true],
              ["审核结论已回", false],
            ]),
            enterNextWhen: mixedGates([["审核通过版本明确", false]]),
            history: [ev("h5", "2026-08-15 09:40", "liuxinyu", "发起审核", "in_progress", "submitted")],
          }),
          item({
            id: "q-art-accept",
            laneId: "q-art",
            stage: "accept",
            state: "not_started",
            dueAt: "2026-08-24",
            offsetLabel: "审核通过后 1-2 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: ["luotianyi"],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["验收结论", false]]),
            enterNextWhen: mixedGates([["验收版本与入库版本一致", false]]),
            history: [],
          }),
          item({
            id: "q-art-checkin",
            laneId: "q-art",
            stage: "checkin",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "yening",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["工程路径已写", false]]),
            enterNextWhen: mixedGates([["交付链结束", false]]),
            history: [],
          }),
        ],
      },
      {
        id: "q-anim",
        name: "Q 版表情动画",
        type: "动画",
        items: [
          item({
            id: "q-anim-launch",
            laneId: "q-anim",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "q-anim-schedule",
            laneId: "q-anim",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-30",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "hanzhou",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("需求已确认"),
            enterNextWhen: doneGates("制作任务明确"),
            history: histSched,
          }),
          item({
            id: "q-anim-produce",
            laneId: "q-anim",
            stage: "produce",
            state: "confirmed",
            dueAt: "2026-08-10",
            offsetLabel: "上线前 11 工作日",
            driId: "hanzhou",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "12 条循环动画" },
            completeWhen: doneGates("动画齐套"),
            enterNextWhen: doneGates("可上传"),
            history: [],
          }),
          item({
            id: "q-anim-upload",
            laneId: "q-anim",
            stage: "upload",
            state: "confirmed",
            dueAt: "2026-08-13",
            offsetLabel: "上线前 9 工作日",
            driId: "hanzhou",
            confirmerId: "liuxinyu",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { svnPath: "svn://art/q-emote/anim", svnRev: "18410" },
            completeWhen: doneGates("版本已登记"),
            enterNextWhen: doneGates("解锁审核"),
            history: [],
          }),
          item({
            id: "q-anim-review",
            laneId: "q-anim",
            stage: "review",
            state: "confirmed",
            dueAt: "2026-08-18",
            offsetLabel: "平台审核预留 3 工作日",
            driId: "liuxinyu",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { conclusion: "平台审核通过" },
            completeWhen: doneGates("审核通过"),
            enterNextWhen: doneGates("解锁验收"),
            history: [ev("ha", "2026-08-17 17:10", "xiangbin", "确认审核通过", "submitted", "confirmed")],
          }),
          item({
            id: "q-anim-accept",
            laneId: "q-anim",
            stage: "accept",
            state: "submitted",
            dueAt: "2026-08-22",
            offsetLabel: "审核通过后 2 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: ["luotianyi"],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "本地验证通过，待确认验收结论" },
            completeWhen: mixedGates([
              ["本地验证完成", true],
              ["验收结论已签", false],
            ]),
            enterNextWhen: mixedGates([["版本一致", true]]),
            history: [ev("hb", "2026-08-18 09:05", "luohaibin", "提交验收", "in_progress", "submitted")],
          }),
          item({
            id: "q-anim-checkin",
            laneId: "q-anim",
            stage: "checkin",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "hanzhou",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["写入工程路径", false]]),
            enterNextWhen: mixedGates([["交付链结束", false]]),
            history: [],
          }),
        ],
      },
      {
        id: "prop3d",
        name: "3D 模型道具",
        type: "3D",
        items: [
          item({
            id: "p3-launch",
            laneId: "prop3d",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "关联夏日家园批次" },
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("后续节点日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "p3-schedule",
            laneId: "prop3d",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-29",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "linguangyi",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "3D 模型道具内容需求表已确认" },
            completeWhen: doneGates("需求表已提交", "需求内容已确认"),
            enterNextWhen: doneGates("制作任务和人员已经明确"),
            history: [
              ev("p3s", "2026-07-29 15:18", "linguangyi", "确认 3D 需求", "submitted", "confirmed"),
            ],
          }),
          item({
            id: "p3-produce",
            laneId: "prop3d",
            stage: "produce",
            state: "confirmed",
            dueAt: "2026-08-13",
            offsetLabel: "须早于上传截止",
            driId: "zhongzhiyong",
            confirmerId: "linguangyi",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "模型已达上传状态" },
            completeWhen: doneGates("必需制作内容齐全"),
            enterNextWhen: doneGates("能够进入 SVN 上传"),
            history: [
              ev("p3p", "2026-08-13 19:44", "linguangyi", "确认制作完成", "submitted", "confirmed"),
            ],
          }),
          item({
            id: "p3-upload",
            laneId: "prop3d",
            stage: "upload",
            state: "in_progress",
            dueAt: "2026-08-17",
            offsetLabel: "上线前 7 工作日（有 IP 则应更早）",
            driId: "zhongzhiyong",
            confirmerId: "liuxinyu",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { svnPath: "svn://art/props/summer", svnRev: "" },
            completeWhen: mixedGates([
              ["必需文件已上传", false],
              ["路径明确", true],
              ["版本已登记", false],
            ]),
            enterNextWhen: mixedGates([["上传完整后解锁审核", false]]),
            history: [
              ev("p3u", "2026-08-16 14:02", "zhongzhiyong", "开始上传", "not_started", "in_progress"),
            ],
          }),
          item({
            id: "p3-review",
            laneId: "prop3d",
            stage: "review",
            state: "not_started",
            dueAt: "2026-08-21",
            offsetLabel: "平台 2-5 工作日；IP 另加",
            driId: "liuxinyu",
            confirmerId: "xiangbin",
            collabIds: ["hepangpang"],
            locked: true,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["适用审核均已通过", false]]),
            enterNextWhen: mixedGates([["通过版本明确", false]]),
            history: [],
          }),
          item({
            id: "p3-accept",
            laneId: "prop3d",
            stage: "accept",
            state: "not_started",
            dueAt: "2026-08-24",
            offsetLabel: "审核通过后 1-2 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: ["luotianyi"],
            locked: true,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["问题关闭", false]]),
            enterNextWhen: mixedGates([["验收版本一致", false]]),
            history: [],
          }),
          item({
            id: "p3-checkin",
            laneId: "prop3d",
            stage: "checkin",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "zhongzhiyong",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: true,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["路径、分支、版本已确认", false]]),
            enterNextWhen: mixedGates([["3D 交付链结束", false]]),
            history: [],
          }),
        ],
      },
      {
        id: "flat2d",
        name: "平面资源",
        type: "2D",
        items: [
          item({
            id: "f2-launch",
            laneId: "flat2d",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "f2-schedule",
            laneId: "flat2d",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-30",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "suwan",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("需求已确认"),
            enterNextWhen: doneGates("人员明确"),
            history: histSched,
          }),
          item({
            id: "f2-produce",
            laneId: "flat2d",
            stage: "produce",
            state: "confirmed",
            dueAt: "2026-08-11",
            offsetLabel: "上线前 10 工作日",
            driId: "suwan",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("切图齐套"),
            enterNextWhen: doneGates("可上传"),
            history: [],
          }),
          item({
            id: "f2-upload",
            laneId: "flat2d",
            stage: "upload",
            state: "confirmed",
            dueAt: "2026-08-14",
            offsetLabel: "上线前 8 工作日",
            driId: "suwan",
            confirmerId: "liuxinyu",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { svnPath: "svn://art/ui/summer", svnRev: "18388" },
            completeWhen: doneGates("版本已登记"),
            enterNextWhen: doneGates("解锁审核"),
            history: [],
          }),
          item({
            id: "f2-review",
            laneId: "flat2d",
            stage: "review",
            state: "confirmed",
            dueAt: "2026-08-18",
            offsetLabel: "平台审核预留 3 工作日",
            driId: "liuxinyu",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { conclusion: "通过" },
            completeWhen: doneGates("审核通过"),
            enterNextWhen: doneGates("解锁验收"),
            history: [],
          }),
          item({
            id: "f2-accept",
            laneId: "flat2d",
            stage: "accept",
            state: "confirmed",
            dueAt: "2026-08-20",
            offsetLabel: "审核通过后 1-2 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: ["luotianyi"],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { conclusion: "验收通过" },
            completeWhen: doneGates("验收通过"),
            enterNextWhen: doneGates("解锁入库"),
            history: [],
          }),
          item({
            id: "f2-checkin",
            laneId: "flat2d",
            stage: "checkin",
            state: "in_progress",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "suwan",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "正在写入工程路径" },
            completeWhen: mixedGates([
              ["最终版本确认", true],
              ["写入工程路径", false],
              ["同步分支", false],
            ]),
            enterNextWhen: mixedGates([["入库完成", false]]),
            history: [ev("f2c", "2026-08-18 10:30", "suwan", "开始入库", "not_started", "in_progress")],
          }),
        ],
      },
      {
        id: "copy",
        name: "家园文案",
        type: "文案",
        items: [
          item({
            id: "cp-launch",
            laneId: "copy",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "cp-schedule",
            laneId: "copy",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-31",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "chenke",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("文案范围已确认"),
            enterNextWhen: doneGates("主责明确"),
            history: histSched,
          }),
          item({
            id: "cp-produce",
            laneId: "copy",
            stage: "produce",
            state: "in_progress",
            dueAt: "2026-08-19",
            offsetLabel: "上线前 5 工作日",
            driId: "chenke",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "家具说明写到一半" },
            completeWhen: mixedGates([
              ["家具说明齐套", false],
              ["活动文案初稿", true],
            ]),
            enterNextWhen: mixedGates([["可进入验收", false]]),
            history: [ev("cp1", "2026-08-12 11:00", "chenke", "开始撰写", "not_started", "in_progress")],
          }),
          item({
            id: "cp-upload",
            laneId: "copy",
            stage: "upload",
            state: "skipped",
            dueAt: "2026-08-19",
            offsetLabel: "文案不走 SVN",
            driId: "chenke",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: true,
            evidence: { note: "模板声明跳过" },
            completeWhen: doneGates("不适用"),
            enterNextWhen: doneGates("跳过"),
            history: [ev("cp0", "2026-07-30 09:00", "xiangbin", "模板跳过上传 SVN", "not_started", "skipped")],
          }),
          item({
            id: "cp-review",
            laneId: "copy",
            stage: "review",
            state: "not_started",
            dueAt: "2026-08-21",
            offsetLabel: "文案校对 2 工作日",
            driId: "xiangbin",
            confirmerId: "longhui",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["校对通过", false]]),
            enterNextWhen: mixedGates([["解锁验收", false]]),
            history: [],
          }),
          item({
            id: "cp-accept",
            laneId: "copy",
            stage: "accept",
            state: "not_started",
            dueAt: "2026-08-24",
            offsetLabel: "校对后 1 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["验收通过", false]]),
            enterNextWhen: mixedGates([["解锁入库", false]]),
            history: [],
          }),
          item({
            id: "cp-checkin",
            laneId: "copy",
            stage: "checkin",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "chenke",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["写入配置表", false]]),
            enterNextWhen: mixedGates([["交付链结束", false]]),
            history: [],
          }),
        ],
      },
      {
        id: "wallpaper",
        name: "常规壁纸",
        type: "2D",
        items: [
          item({
            id: "wp-launch",
            laneId: "wallpaper",
            stage: "launch",
            state: "confirmed",
            dueAt: "2026-07-28",
            offsetLabel: "上线日确认时",
            driId: "longhui",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("上线日期已确认"),
            enterNextWhen: doneGates("日期已换算"),
            history: histLaunch,
          }),
          item({
            id: "wp-schedule",
            laneId: "wallpaper",
            stage: "schedule",
            state: "confirmed",
            dueAt: "2026-07-30",
            offsetLabel: "上线前 4 周",
            driId: "xiangbin",
            confirmerId: "jiangxia",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: {},
            completeWhen: doneGates("主题已确认"),
            enterNextWhen: doneGates("制作任务明确"),
            history: histSched,
          }),
          item({
            id: "wp-produce",
            laneId: "wallpaper",
            stage: "produce",
            state: "in_progress",
            dueAt: "2026-08-22",
            offsetLabel: "上线前 3 工作日",
            driId: "jiangxia",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: false,
            skipped: false,
            evidence: { note: "白天版已出，夜晚版绘制中" },
            completeWhen: mixedGates([
              ["白天版", true],
              ["夜晚版", false],
            ]),
            enterNextWhen: mixedGates([["可上传", false]]),
            history: [ev("wp1", "2026-08-10 10:00", "jiangxia", "开始绘制", "not_started", "in_progress")],
          }),
          item({
            id: "wp-upload",
            laneId: "wallpaper",
            stage: "upload",
            state: "not_started",
            dueAt: "2026-08-22",
            offsetLabel: "制作完成后当日",
            driId: "jiangxia",
            confirmerId: "liuxinyu",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["版本已登记", false]]),
            enterNextWhen: mixedGates([["解锁审核", false]]),
            history: [],
          }),
          item({
            id: "wp-review",
            laneId: "wallpaper",
            stage: "review",
            state: "not_started",
            dueAt: "2026-08-24",
            offsetLabel: "平台审核 2 工作日",
            driId: "liuxinyu",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["审核通过", false]]),
            enterNextWhen: mixedGates([["解锁验收", false]]),
            history: [],
          }),
          item({
            id: "wp-accept",
            laneId: "wallpaper",
            stage: "accept",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "审核通过后 1 工作日",
            driId: "luohaibin",
            confirmerId: "xiangbin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["验收通过", false]]),
            enterNextWhen: mixedGates([["解锁入库", false]]),
            history: [],
          }),
          item({
            id: "wp-checkin",
            laneId: "wallpaper",
            stage: "checkin",
            state: "not_started",
            dueAt: "2026-08-25",
            offsetLabel: "不晚于上线前 1 天",
            driId: "jiangxia",
            confirmerId: "luohaibin",
            collabIds: [],
            locked: false,
            waiting: true,
            skipped: false,
            evidence: {},
            completeWhen: mixedGates([["写入工程路径", false]]),
            enterNextWhen: mixedGates([["交付链结束", false]]),
            history: [],
          }),
        ],
      },
      ...overflowLanes(),
    ],
  };
}

const STAGE_ORDER: StageKey[] = ["launch", "schedule", "produce", "upload", "review", "accept", "checkin"];

function stubLane(
  id: string,
  name: string,
  type: string,
  current: StageKey,
  driId: PersonId,
  dueAt: string,
): ResourceLane {
  const idx = STAGE_ORDER.indexOf(current);
  return {
    id,
    name,
    type,
    items: STAGE_ORDER.map((stage, i) =>
      item({
        id: `${id}-${stage}`,
        laneId: id,
        stage,
        state: i < idx ? "confirmed" : i === idx ? "in_progress" : "not_started",
        dueAt: i < idx ? "2026-08-10" : dueAt,
        offsetLabel: "相对上线日",
        driId: i <= 1 ? "xiangbin" : driId,
        confirmerId: "xiangbin",
        collabIds: [],
        locked: false,
        waiting: i > idx,
        skipped: false,
        evidence: {},
        completeWhen: i < idx ? doneGates("已完成") : mixedGates([["待交付", false]]),
        enterNextWhen: i < idx ? doneGates("已流转") : mixedGates([["可流转", false]]),
        history: i === 0 ? histLaunch : i === 1 ? histSched : [],
      }),
    ),
  };
}

function overflowLanes(): ResourceLane[] {
  return [
    stubLane("frame", "节日边框超长名称需要省略显示", "2D", "produce", "suwan", "2026-08-22"),
    stubLane("loader", "加载页插画", "2D", "produce", "yening", "2026-08-21"),
    stubLane("shop", "商店图标", "2D", "produce", "suwan", "2026-08-23"),
    stubLane("banner", "活动 Banner", "2D", "produce", "jiangxia", "2026-08-22"),
    stubLane("login", "登录背景", "2D", "produce", "jiangxia", "2026-08-24"),
    stubLane("badge", "徽章图标", "2D", "review", "liuxinyu", "2026-08-21"),
    stubLane("mail", "邮件头图", "2D", "review", "liuxinyu", "2026-08-22"),
    stubLane("popup", "弹窗装饰", "2D", "accept", "luohaibin", "2026-08-25"),
  ];
}

export function seedQuietBatch(): LaunchBatch {
  const src = seedPrimaryBatch();
  return {
    id: "b-quiet",
    name: "2026 九月常规周更",
    subtitle: "对照批次 · 无红灯",
    launchDate: "2026-09-16",
    batchDriId: "xiangbin",
    lanes: src.lanes.slice(0, 3).map((lane) => ({
      ...lane,
      id: `${lane.id}-q`,
      items: lane.items.map((it) => ({
        ...it,
        id: `${it.id}-q`,
        laneId: `${lane.id}-q`,
        state: it.stage === "checkin" ? "in_progress" : "confirmed",
        locked: false,
        waiting: it.stage === "checkin",
        dueAt: it.stage === "checkin" ? "2026-09-15" : it.dueAt,
        completeWhen: it.completeWhen.map((g) => ({ ...g, ok: it.stage !== "checkin" || g.ok })),
      })),
    })),
  };
}

export const PREVIEW_ROLES: Array<{ id: PersonId; label: string }> = [
  { id: "xiangbin", label: "向彬 · 制片" },
  { id: "zhongzhiyong", label: "钟志勇 · 制作" },
  { id: "luohaibin", label: "罗海彬 · 验收" },
  { id: "liuxinyu", label: "刘心语 · 送审" },
  { id: "chenke", label: "陈可 · 文案" },
];
