/** Ant Design 6 default seed / preset colors. */
export const palette = {
  blue: "#1677ff",
  geekblue: "#2f54eb",
  purple: "#722ed1",
  cyan: "#13c2c2",
  green: "#52c41a",
  magenta: "#eb2f96",
  red: "#ff4d4f",
  volcano: "#fa541c",
  orange: "#fa8c16",
  gold: "#faad14",
  lime: "#a0d911",
  gray: "rgba(0, 0, 0, 0.45)",
  gray5: "#f0f0f0",
  gray6: "#f5f5f5",
  border: "#d9d9d9",
  split: "#f0f0f0",
  label: "rgba(0, 0, 0, 0.88)",
  secondaryLabel: "rgba(0, 0, 0, 0.65)",
  layout: "#f5f5f5",
  surface: "#ffffff",
} as const;

export const AVATAR_COLORS = [
  palette.blue,
  palette.geekblue,
  palette.purple,
  palette.magenta,
  palette.red,
  palette.orange,
  palette.green,
  palette.cyan,
  palette.gold,
  palette.volcano,
] as const;
